export const ALL_PRODUCTS_REQUEST ="ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS ="ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAILURE ="ALL_PRODUCTS_FAILURE";

export const PRODUCT_DETAILS_REQUEST ="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS ="PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILURE ="PRODUCT_DETAILS_FAILURE";

export const ADMIN_PRODUCTS_REQUEST="ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCTS_SUCCESS ="ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCTS_FAILURE ="ADMIN_PRODUCT_FAILURE";

export const NEW_PRODUCT_REQUEST ="NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS ="NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET ="NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAILURE ="NEW_PRODUCT_FAILURE";

export const CLEAR_ERRORS ="CLEAR_ERRORS";
